// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgefzahqcgqyxwiemous.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZWZ6YWhxY2dxeXh3aWVtb3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTgzMjAsImV4cCI6MjA2NTA3NDMyMH0.eyut_sxyD_MLHyXQyNEB3kx50NmuH4sMwUTceMOlcsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);